"""empty message

Revision ID: f1d143bd861d
Revises: 1196c26d2fb1
Create Date: 2023-08-30 17:22:24.948458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d143bd861d'
down_revision = '1196c26d2fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlistsong',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlistsong_playlist_id_playlists')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_playlistsong_song_id_songs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playlist_song')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('Songs')

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Songs', sa.TEXT(), nullable=True))

    op.create_table('playlist_song',
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='fk_playlist_song_playlist_id_playlists'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='fk_playlist_song_song_id_songs'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    op.drop_table('playlistsong')
    # ### end Alembic commands ###
